name: HabitTracker iOS CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test-upload:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Resolve SPM dependencies
        run: xcodebuild -resolvePackageDependencies -project HabitTracker/HabitTracker.xcodeproj -scheme HabitTracker

      - name: Build project
        run: |
          xcodebuild clean build \
            -project HabitTracker/HabitTracker.xcodeproj \
            -scheme HabitTracker \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro'

      - name: Run tests
        run: |
          xcodebuild test \
            -project HabitTracker/HabitTracker.xcodeproj \
            -scheme HabitTracker \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro'
